import asyncio
from datetime import datetime
import random

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert

from db.postgres import AsyncSessionLocal, init_db
from db.postgres_models import Company, StockQuote

# Top 200 NSE stocks with market cap
NSE_STOCKS = [
    {
        "symbol": "RELIANCE",
        "nse_code": "RELIANCE",
        "name": "Reliance Industries Ltd",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "market_cap": 2012500000000,
    },
    {
        "symbol": "TCS",
        "nse_code": "TCS",
        "name": "Tata Consultancy Services Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 1520000000000,
    },
    {
        "symbol": "HDFCBANK",
        "nse_code": "HDFCBANK",
        "name": "HDFC Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 1250000000000,
    },
    {
        "symbol": "INFY",
        "nse_code": "INFY",
        "name": "Infosys Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 780000000000,
    },
    {
        "symbol": "ICICIBANK",
        "nse_code": "ICICIBANK",
        "name": "ICICI Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 685000000000,
    },
    {
        "symbol": "SBIN",
        "nse_code": "SBIN",
        "name": "State Bank of India",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 650000000000,
    },
    {
        "symbol": "WIPRO",
        "nse_code": "WIPRO",
        "name": "Wipro Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 285000000000,
    },
    {
        "symbol": "LT",
        "nse_code": "LT",
        "name": "Larsen & Toubro Ltd",
        "sector": "Capital Goods",
        "industry": "Construction",
        "market_cap": 450000000000,
    },
    {
        "symbol": "HINDUNILVR",
        "nse_code": "HINDUNILVR",
        "name": "Hindustan Unilever Ltd",
        "sector": "FMCG",
        "industry": "Consumer Goods",
        "market_cap": 565000000000,
    },
    {
        "symbol": "KOTAKBANK",
        "nse_code": "KOTAKBANK",
        "name": "Kotak Mahindra Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 355000000000,
    },
    {
        "symbol": "BHARTIARTL",
        "nse_code": "BHARTIARTL",
        "name": "Bharti Airtel Ltd",
        "sector": "Telecommunication",
        "industry": "Telecom Services",
        "market_cap": 920000000000,
    },
    {
        "symbol": "HCLTECH",
        "nse_code": "HCLTECH",
        "name": "HCL Technologies Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 495000000000,
    },
    {
        "symbol": "MARUTI",
        "nse_code": "MARUTI",
        "name": "Maruti Suzuki India Ltd",
        "sector": "Automobile",
        "industry": "Automobiles",
        "market_cap": 385000000000,
    },
    {
        "symbol": "TITAN",
        "nse_code": "TITAN",
        "name": "Titan Company Ltd",
        "sector": "Consumer Goods",
        "industry": "Jewelry",
        "market_cap": 340000000000,
    },
    {
        "symbol": "BAJFINANCE",
        "nse_code": "BAJFINANCE",
        "name": "Bajaj Finance Ltd",
        "sector": "Financial Services",
        "industry": "NBFC",
        "market_cap": 485000000000,
    },
    {
        "symbol": "TATASTEEL",
        "nse_code": "TATASTEEL",
        "name": "Tata Steel Ltd",
        "sector": "Metals",
        "industry": "Steel",
        "market_cap": 185000000000,
    },
    {
        "symbol": "AXISBANK",
        "nse_code": "AXISBANK",
        "name": "Axis Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 380000000000,
    },
    {
        "symbol": "SUNPHARMA",
        "nse_code": "SUNPHARMA",
        "name": "Sun Pharmaceutical Industries Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 445000000000,
    },
    {
        "symbol": "NESTLEIND",
        "nse_code": "NESTLEIND",
        "name": "Nestle India Ltd",
        "sector": "FMCG",
        "industry": "Food Products",
        "market_cap": 235000000000,
    },
    {
        "symbol": "M&M",
        "nse_code": "M&M",
        "name": "Mahindra & Mahindra Ltd",
        "sector": "Automobile",
        "industry": "Automobiles",
        "market_cap": 385000000000,
    },
    {
        "symbol": "TATAMOTORS",
        "nse_code": "TATAMOTORS",
        "name": "Tata Motors Ltd",
        "sector": "Automobile",
        "industry": "Automobiles",
        "market_cap": 195000000000,
    },
    {
        "symbol": "ADANIPORTS",
        "nse_code": "ADANIPORTS",
        "name": "Adani Ports and SEZ Ltd",
        "sector": "Services",
        "industry": "Ports & Shipping",
        "market_cap": 295000000000,
    },
    {
        "symbol": "ULTRACEMCO",
        "nse_code": "ULTRACEMCO",
        "name": "UltraTech Cement Ltd",
        "sector": "Materials",
        "industry": "Cement",
        "market_cap": 285000000000,
    },
    {
        "symbol": "INDUSINDBK",
        "nse_code": "INDUSINDBK",
        "name": "IndusInd Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 225000000000,
    },
    {
        "symbol": "JSWSTEEL",
        "nse_code": "JSWSTEEL",
        "name": "JSW Steel Ltd",
        "sector": "Metals",
        "industry": "Steel",
        "market_cap": 195000000000,
    },
    {
        "symbol": "TECHM",
        "nse_code": "TECHM",
        "name": "Tech Mahindra Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 145000000000,
    },
    {
        "symbol": "HINDALCO",
        "nse_code": "HINDALCO",
        "name": "Hindalco Industries Ltd",
        "sector": "Metals",
        "industry": "Aluminum",
        "market_cap": 175000000000,
    },
    {
        "symbol": "CIPLA",
        "nse_code": "CIPLA",
        "name": "Cipla Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 115000000000,
    },
    {
        "symbol": "DRREDDY",
        "nse_code": "DRREDDY",
        "name": "Dr. Reddy's Laboratories Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 115000000000,
    },
    {
        "symbol": "ADANIENSOL",
        "nse_code": "ADANIENSOL",
        "name": "Adani Energy Solutions Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 265000000000,
    },
    # Additional 170 stocks
    {
        "symbol": "POWERGRID",
        "nse_code": "POWERGRID",
        "name": "Power Grid Corporation of India Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 285000000000,
    },
    {
        "symbol": "NTPC",
        "nse_code": "NTPC",
        "name": "NTPC Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 365000000000,
    },
    {
        "symbol": "ONGC",
        "nse_code": "ONGC",
        "name": "Oil & Natural Gas Corporation Ltd",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "market_cap": 285000000000,
    },
    {
        "symbol": "COALINDIA",
        "nse_code": "COALINDIA",
        "name": "Coal India Ltd",
        "sector": "Energy",
        "industry": "Mining",
        "market_cap": 265000000000,
    },
    {
        "symbol": "IOC",
        "nse_code": "IOC",
        "name": "Indian Oil Corporation Ltd",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "market_cap": 195000000000,
    },
    {
        "symbol": "BPCL",
        "nse_code": "BPCL",
        "name": "Bharat Petroleum Corporation Ltd",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "market_cap": 145000000000,
    },
    {
        "symbol": "HPCL",
        "nse_code": "HPCL",
        "name": "Hindustan Petroleum Corporation Ltd",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "market_cap": 95000000000,
    },
    {
        "symbol": "ITC",
        "nse_code": "ITC",
        "name": "ITC Ltd",
        "sector": "FMCG",
        "industry": "Consumer Goods",
        "market_cap": 585000000000,
    },
    {
        "symbol": "BRITANNIA",
        "nse_code": "BRITANNIA",
        "name": "Britannia Industries Ltd",
        "sector": "FMCG",
        "industry": "Food Products",
        "market_cap": 145000000000,
    },
    {
        "symbol": "DABUR",
        "nse_code": "DABUR",
        "name": "Dabur India Ltd",
        "sector": "FMCG",
        "industry": "Consumer Goods",
        "market_cap": 105000000000,
    },
    {
        "symbol": "COLPAL",
        "nse_code": "COLPAL",
        "name": "Colgate-Palmolive India Ltd",
        "sector": "FMCG",
        "industry": "Consumer Goods",
        "market_cap": 65000000000,
    },
    {
        "symbol": "GODREJCP",
        "nse_code": "GODREJCP",
        "name": "Godrej Consumer Products Ltd",
        "sector": "FMCG",
        "industry": "Consumer Goods",
        "market_cap": 125000000000,
    },
    {
        "symbol": "TATACONS",
        "nse_code": "TATACONS",
        "name": "Tata Consumer Products Ltd",
        "sector": "FMCG",
        "industry": "Food Products",
        "market_cap": 115000000000,
    },
    {
        "symbol": "BAJAJFINSV",
        "nse_code": "BAJAJFINSV",
        "name": "Bajaj Finserv Ltd",
        "sector": "Financial Services",
        "industry": "NBFC",
        "market_cap": 345000000000,
    },
    {
        "symbol": "BAJAJ_AUTO",
        "nse_code": "BAJAJ_AUTO",
        "name": "Bajaj Auto Ltd",
        "sector": "Automobile",
        "industry": "Automobiles",
        "market_cap": 265000000000,
    },
    {
        "symbol": "EICHERMOT",
        "nse_code": "EICHERMOT",
        "name": "Eicher Motors Ltd",
        "sector": "Automobile",
        "industry": "Automobiles",
        "market_cap": 145000000000,
    },
    {
        "symbol": "HEROMOTOCO",
        "nse_code": "HEROMOTOCO",
        "name": "Hero MotoCorp Ltd",
        "sector": "Automobile",
        "industry": "Automobiles",
        "market_cap": 75000000000,
    },
    {
        "symbol": "TVSMOTOR",
        "nse_code": "TVSMOTOR",
        "name": "TVS Motor Company Ltd",
        "sector": "Automobile",
        "industry": "Automobiles",
        "market_cap": 95000000000,
    },
    {
        "symbol": "ASHOKLEY",
        "nse_code": "ASHOKLEY",
        "name": "Ashok Leyland Ltd",
        "sector": "Automobile",
        "industry": "Commercial Vehicles",
        "market_cap": 65000000000,
    },
    {
        "symbol": "MOTHERSUMI",
        "nse_code": "MOTHERSUMI",
        "name": "Motherson Sumi Systems Ltd",
        "sector": "Automobile",
        "industry": "Auto Components",
        "market_cap": 75000000000,
    },
    {
        "symbol": "BALKRISIND",
        "nse_code": "BALKRISIND",
        "name": "Balkrishna Industries Ltd",
        "sector": "Automobile",
        "industry": "Tyres",
        "market_cap": 55000000000,
    },
    {
        "symbol": "APOLLOTYRE",
        "nse_code": "APOLLOTYRE",
        "name": "Apollo Tyres Ltd",
        "sector": "Automobile",
        "industry": "Tyres",
        "market_cap": 45000000000,
    },
    {
        "symbol": "MRF",
        "nse_code": "MRF",
        "name": "MRF Ltd",
        "sector": "Automobile",
        "industry": "Tyres",
        "market_cap": 65000000000,
    },
    {
        "symbol": "GRASIM",
        "nse_code": "GRASIM",
        "name": "Grasim Industries Ltd",
        "sector": "Materials",
        "industry": "Cement",
        "market_cap": 185000000000,
    },
    {
        "symbol": "SHREECEM",
        "nse_code": "SHREECEM",
        "name": "Shree Cement Ltd",
        "sector": "Materials",
        "industry": "Cement",
        "market_cap": 95000000000,
    },
    {
        "symbol": "AMBUJACEM",
        "nse_code": "AMBUJACEM",
        "name": "Ambuja Cements Ltd",
        "sector": "Materials",
        "industry": "Cement",
        "market_cap": 85000000000,
    },
    {
        "symbol": "ACC",
        "nse_code": "ACC",
        "name": "ACC Ltd",
        "sector": "Materials",
        "industry": "Cement",
        "market_cap": 45000000000,
    },
    {
        "symbol": "DALBHARAT",
        "nse_code": "DALBHARAT",
        "name": "Dalmia Bharat Cement Ltd",
        "sector": "Materials",
        "industry": "Cement",
        "market_cap": 35000000000,
    },
    {
        "symbol": "SAIL",
        "nse_code": "SAIL",
        "name": "Steel Authority of India Ltd",
        "sector": "Metals",
        "industry": "Steel",
        "market_cap": 75000000000,
    },
    {
        "symbol": "TATAINVEST",
        "nse_code": "TATAINVEST",
        "name": "Tata Investment Corporation Ltd",
        "sector": "Financial Services",
        "industry": "Investment",
        "market_cap": 45000000000,
    },
    {
        "symbol": "TIDCO",
        "nse_code": "TIDCO",
        "name": "Titagarh Wagons Ltd",
        "sector": "Capital Goods",
        "industry": "Engineering",
        "market_cap": 25000000000,
    },
    {
        "symbol": "BHEL",
        "nse_code": "BHEL",
        "name": "Bharat Heavy Electricals Ltd",
        "sector": "Capital Goods",
        "industry": "Engineering",
        "market_cap": 95000000000,
    },
    {
        "symbol": "LTH",
        "nse_code": "LTH",
        "name": "L&T Technology Services Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 35000000000,
    },
    {
        "symbol": "HAVELLS",
        "nse_code": "HAVELLS",
        "name": "Havells India Ltd",
        "sector": "Consumer Goods",
        "industry": "Electricals",
        "market_cap": 145000000000,
    },
    {
        "symbol": "VOLTAS",
        "nse_code": "VOLTAS",
        "name": "Voltas Ltd",
        "sector": "Consumer Goods",
        "industry": "Electronics",
        "market_cap": 45000000000,
    },
    {
        "symbol": "WHIRLPOOL",
        "nse_code": "WHIRLPOOL",
        "name": "Whirlpool of India Ltd",
        "sector": "Consumer Goods",
        "industry": "Consumer Durables",
        "market_cap": 35000000000,
    },
    {
        "symbol": "LG",
        "nse_code": "LG",
        "name": "LG India",
        "sector": "Consumer Goods",
        "industry": "Electronics",
        "market_cap": 0,
    },
    {
        "symbol": "SAMSUNG",
        "nse_code": "SAMSUNG",
        "name": "Samsung India",
        "sector": "Consumer Goods",
        "industry": "Electronics",
        "market_cap": 0,
    },
    {
        "symbol": "PIDILITIND",
        "nse_code": "PIDILITIND",
        "name": "Pidilite Industries Ltd",
        "sector": "Materials",
        "industry": "Chemicals",
        "market_cap": 145000000000,
    },
    {
        "symbol": "UPL",
        "nse_code": "UPL",
        "name": "UPL Ltd",
        "sector": "Materials",
        "industry": "Agrochemicals",
        "market_cap": 55000000000,
    },
    {
        "symbol": "PIIND",
        "nse_code": "PIIND",
        "name": "PI Industries Ltd",
        "sector": "Materials",
        "industry": "Agrochemicals",
        "market_cap": 65000000000,
    },
    {
        "symbol": "TATACHEM",
        "nse_code": "TATACHEM",
        "name": "Tata Chemicals Ltd",
        "sector": "Materials",
        "industry": "Chemicals",
        "market_cap": 35000000000,
    },
    {
        "symbol": "DEEPAKNTR",
        "nse_code": "DEEPAKNTR",
        "name": "Deepak Nitrite Ltd",
        "sector": "Materials",
        "industry": "Chemicals",
        "market_cap": 55000000000,
    },
    {
        "symbol": "ATUL",
        "nse_code": "ATUL",
        "name": "Atul Ltd",
        "sector": "Materials",
        "industry": "Chemicals",
        "market_cap": 25000000000,
    },
    {
        "symbol": "SUPRAJIT",
        "nse_code": "SUPRAJIT",
        "name": "Suprajit Engineering Ltd",
        "sector": "Automobile",
        "industry": "Auto Components",
        "market_cap": 15000000000,
    },
    {
        "symbol": "MGL",
        "nse_code": "MGL",
        "name": "Mahanagar Gas Ltd",
        "sector": "Energy",
        "industry": "Gas Distribution",
        "market_cap": 25000000000,
    },
    {
        "symbol": "GAIL",
        "nse_code": "GAIL",
        "name": "GAIL India Ltd",
        "sector": "Energy",
        "industry": "Gas Transmission",
        "market_cap": 145000000000,
    },
    {
        "symbol": "PNB",
        "nse_code": "PNB",
        "name": "Punjab National Bank",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 85000000000,
    },
    {
        "symbol": "CANBK",
        "nse_code": "CANBK",
        "name": "Canara Bank",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 95000000000,
    },
    {
        "symbol": "UNIONBANK",
        "nse_code": "UNIONBANK",
        "name": "Union Bank of India",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 75000000000,
    },
    {
        "symbol": "BANKBARODA",
        "nse_code": "BANKBARODA",
        "name": "Bank of Baroda",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 145000000000,
    },
    {
        "symbol": "IDBIBANK",
        "nse_code": "IDBIBANK",
        "name": "IDBI Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 85000000000,
    },
    {
        "symbol": "BANDHANBNK",
        "nse_code": "BANDHANBNK",
        "name": "Bandhan Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 75000000000,
    },
    {
        "symbol": "RBLBANK",
        "nse_code": "RBLBANK",
        "name": "RBL Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 45000000000,
    },
    {
        "symbol": "FEDERALBNK",
        "nse_code": "FEDERALBNK",
        "name": "Federal Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 55000000000,
    },
    {
        "symbol": "YESBANK",
        "nse_code": "YESBANK",
        "name": "Yes Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 45000000000,
    },
    {
        "symbol": "IDFCFIRSTB",
        "nse_code": "IDFCFIRSTB",
        "name": "IDFC First Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 65000000000,
    },
    {
        "symbol": "SBICARD",
        "nse_code": "SBICARD",
        "name": "SBI Cards and Payment Services Ltd",
        "sector": "Financial Services",
        "industry": "Credit Cards",
        "market_cap": 145000000000,
    },
    {
        "symbol": "SBILIFE",
        "nse_code": "SBILIFE",
        "name": "SBI Life Insurance Company Ltd",
        "sector": "Financial Services",
        "industry": "Insurance",
        "market_cap": 165000000000,
    },
    {
        "symbol": "HDFCLIFE",
        "nse_code": "HDFCLIFE",
        "name": "HDFC Life Insurance Company Ltd",
        "sector": "Financial Services",
        "industry": "Insurance",
        "market_cap": 145000000000,
    },
    {
        "symbol": "ICICIPRULI",
        "nse_code": "ICICIPRULI",
        "name": "ICICI Prudential Life Insurance",
        "sector": "Financial Services",
        "industry": "Insurance",
        "market_cap": 115000000000,
    },
    {
        "symbol": "BAJAJINS",
        "nse_code": "BAJAJINS",
        "name": "Bajaj Allianz General Insurance",
        "sector": "Financial Services",
        "industry": "Insurance",
        "market_cap": 85000000000,
    },
    {
        "symbol": "ICICIGI",
        "nse_code": "ICICIGI",
        "name": "ICICI Lombard General Insurance",
        "sector": "Financial Services",
        "industry": "Insurance",
        "market_cap": 145000000000,
    },
    {
        "symbol": "TATAELXSI",
        "nse_code": "TATAELXSI",
        "name": "Tata Elxsi Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 65000000000,
    },
    {
        "symbol": "LTI",
        "nse_code": "LTI",
        "name": "L&T Infotech Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 55000000000,
    },
    {
        "symbol": "MINDTREE",
        "nse_code": "MINDTREE",
        "name": "Mphasis Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 45000000000,
    },
    {
        "symbol": "PERSISTENT",
        "nse_code": "PERSISTENT",
        "name": "Persistent Systems Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 55000000000,
    },
    {
        "symbol": "COFORGE",
        "nse_code": "COFORGE",
        "name": "Coforge Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 45000000000,
    },
    {
        "symbol": "MPHASIS",
        "nse_code": "MPHASIS",
        "name": "Mphasis Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 45000000000,
    },
    {
        "symbol": "CYIENT",
        "nse_code": "CYIENT",
        "name": "Cyient Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 15000000000,
    },
    {
        "symbol": "NEWGEN",
        "nse_code": "NEWGEN",
        "name": "Newgen Software Technologies Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 12000000000,
    },
    {
        "symbol": "TANLA",
        "nse_code": "TANLA",
        "name": "Tanla Platforms Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 18000000000,
    },
    {
        "symbol": "OFSS",
        "nse_code": "OFSS",
        "name": "Oracle Financial Services Software Ltd",
        "sector": "Technology",
        "industry": "IT Services",
        "market_cap": 45000000000,
    },
    {
        "symbol": "JUSTDIAL",
        "nse_code": "JUSTDIAL",
        "name": "Just Dial Ltd",
        "sector": "Services",
        "industry": "Information Technology",
        "market_cap": 8500000000,
    },
    {
        "symbol": "RELAXO",
        "nse_code": "RELAXO",
        "name": "Relaxo Footwears Ltd",
        "sector": "Consumer Goods",
        "industry": "Footwear",
        "market_cap": 25000000000,
    },
    {
        "symbol": "BATAINDIA",
        "nse_code": "BATAINDIA",
        "name": "Bata India Ltd",
        "sector": "Consumer Goods",
        "industry": "Footwear",
        "market_cap": 35000000000,
    },
    {
        "symbol": "LIBERTSHOE",
        "nse_code": "LIBERTSHOE",
        "name": "Liberty Shoes Ltd",
        "sector": "Consumer Goods",
        "industry": "Footwear",
        "market_cap": 5000000000,
    },
    {
        "symbol": "ABFRL",
        "nse_code": "ABFRL",
        "name": "Aditya Birla Fashion and Retail Ltd",
        "sector": "Consumer Goods",
        "industry": "Apparel",
        "market_cap": 35000000000,
    },
    {
        "symbol": "PAGEIND",
        "nse_code": "PAGEIND",
        "name": "Page Industries Ltd",
        "sector": "Consumer Goods",
        "industry": "Apparel",
        "market_cap": 55000000000,
    },
    {
        "symbol": "TRENT",
        "nse_code": "TRENT",
        "name": "Trent Ltd",
        "sector": "Consumer Goods",
        "industry": "Retail",
        "market_cap": 65000000000,
    },
    {
        "symbol": "ZOMATO",
        "nse_code": "ZOMATO",
        "name": "Zomato Ltd",
        "sector": "Services",
        "industry": "Food Delivery",
        "market_cap": 250000000000,
    },
    {
        "symbol": "SWIGGY",
        "nse_code": "SWIGGY",
        "name": "Swiggy Ltd",
        "sector": "Services",
        "industry": "Food Delivery",
        "market_cap": 150000000000,
    },
    {
        "symbol": "DMART",
        "nse_code": "DMART",
        "name": "Avenue Supermarts Ltd",
        "sector": "Services",
        "industry": "Retail",
        "market_cap": 285000000000,
    },
    {
        "symbol": "JUBLFOOD",
        "nse_code": "JUBLFOOD",
        "name": "Jubilant Foodworks Ltd",
        "sector": "Services",
        "industry": "Food Services",
        "market_cap": 35000000000,
    },
    {
        "symbol": "DEVYANI",
        "nse_code": "DEVYANI",
        "name": "Devyani International Ltd",
        "sector": "Services",
        "industry": "Food Services",
        "market_cap": 25000000000,
    },
    {
        "symbol": "RATEGAIN",
        "nse_code": "RATEGAIN",
        "name": "RateGain Travel Technologies Ltd",
        "sector": "Technology",
        "industry": "Travel Tech",
        "market_cap": 15000000000,
    },
    {
        "symbol": "ETERNAL",
        "nse_code": "ETERNAL",
        "name": "Eternal Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 35000000000,
    },
    {
        "symbol": "DIVISLAB",
        "nse_code": "DIVISLAB",
        "name": "Divi's Laboratories Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 145000000000,
    },
    {
        "symbol": "ABBOTTIND",
        "nse_code": "ABBOTTIND",
        "name": "Abbott India Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 85000000000,
    },
    {
        "symbol": "BANDHANBNK",
        "nse_code": "BANDHANBNK",
        "name": "Bandhan Bank Ltd",
        "sector": "Financial Services",
        "industry": "Banking",
        "market_cap": 75000000000,
    },
    {
        "symbol": "MANKIND",
        "nse_code": "MANKIND",
        "name": "Mankind Pharma Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 95000000000,
    },
    {
        "symbol": "ASTERDM",
        "nse_code": "ASTERDM",
        "name": "Aster DM Healthcare Ltd",
        "sector": "Healthcare",
        "industry": "Healthcare Services",
        "market_cap": 35000000000,
    },
    {
        "symbol": "METROPOLIS",
        "nse_code": "METROPOLIS",
        "name": "Metropolis Healthcare Ltd",
        "sector": "Healthcare",
        "industry": "Diagnostics",
        "market_cap": 12000000000,
    },
    {
        "symbol": "THYROCAR",
        "nse_code": "THYROCAR",
        "name": "Thyrocare Technologies Ltd",
        "sector": "Healthcare",
        "industry": "Diagnostics",
        "market_cap": 8000000000,
    },
    {
        "symbol": "LUPIN",
        "nse_code": "LUPIN",
        "name": "Lupin Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 65000000000,
    },
    {
        "symbol": "GLAND",
        "nse_code": "GLAND",
        "name": "Gland Pharma Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 45000000000,
    },
    {
        "symbol": "ALKEM",
        "nse_code": "ALKEM",
        "name": "Alkem Laboratories Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 75000000000,
    },
    {
        "symbol": "APLLTD",
        "nse_code": "APLLTD",
        "name": "Aurobindo Pharma Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 55000000000,
    },
    {
        "symbol": "TORNTPHARM",
        "nse_code": "TORNTPHARM",
        "name": "Torrent Pharmaceuticals Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 85000000000,
    },
    {
        "symbol": "GLaxo",
        "nse_code": "GLaxo",
        "name": "GlaxoSmithKline Pharmaceuticals Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 35000000000,
    },
    {
        "symbol": "PFIZER",
        "nse_code": "PFIZER",
        "name": "Pfizer Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 25000000000,
    },
    {
        "symbol": "SANOFI",
        "nse_code": "SANOFI",
        "name": "Sanofi India Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 25000000000,
    },
    {
        "symbol": "JBCHEPHARM",
        "nse_code": "JBCHEPHARM",
        "name": "JB Chemicals & Pharmaceuticals Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 25000000000,
    },
    {
        "symbol": "CAPLIPOINT",
        "nse_code": "CAPLIPOINT",
        "name": "Caplin Point Laboratories Ltd",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "market_cap": 18000000000,
    },
    {
        "symbol": "BPCL",
        "nse_code": "BPCL",
        "name": "Bharat Petroleum Corporation Ltd",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "market_cap": 145000000000,
    },
    {
        "symbol": "IGL",
        "nse_code": "IGL",
        "name": "Indraprastha Gas Ltd",
        "sector": "Energy",
        "industry": "Gas Distribution",
        "market_cap": 85000000000,
    },
    {
        "symbol": "MGL",
        "nse_code": "MGL",
        "name": "Mahanagar Gas Ltd",
        "sector": "Energy",
        "industry": "Gas Distribution",
        "market_cap": 25000000000,
    },
    {
        "symbol": "GUJGA",
        "nse_code": "GUJGA",
        "name": "Gujarat Gas Ltd",
        "sector": "Energy",
        "industry": "Gas Distribution",
        "market_cap": 55000000000,
    },
    {
        "symbol": "ADANIGREEN",
        "nse_code": "ADANIGREEN",
        "name": "Adani Green Energy Ltd",
        "sector": "Energy",
        "industry": "Renewable Power",
        "market_cap": 285000000000,
    },
    {
        "symbol": "ADANIPOWER",
        "nse_code": "ADANIPOWER",
        "name": "Adani Power Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 145000000000,
    },
    {
        "symbol": "TATAPOWER",
        "nse_code": "TATAPOWER",
        "name": "Tata Power Company Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 145000000000,
    },
    {
        "symbol": "TORNTPOWER",
        "nse_code": "TORNTPOWER",
        "name": "Torrent Power Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 95000000000,
    },
    {
        "symbol": "NLCINDIA",
        "nse_code": "NLCINDIA",
        "name": "NLC India Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 35000000000,
    },
    {
        "symbol": "NHPC",
        "nse_code": "NHPC",
        "name": "NHPC Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 65000000000,
    },
    {
        "symbol": "SJVN",
        "nse_code": "SJVN",
        "name": "SJVN Ltd",
        "sector": "Energy",
        "industry": "Power",
        "market_cap": 45000000000,
    },
    {
        "symbol": "NBCC",
        "nse_code": "NBCC",
        "name": "NBCC India Ltd",
        "sector": "Capital Goods",
        "industry": "Construction",
        "market_cap": 35000000000,
    },
    {
        "symbol": "IRCTC",
        "nse_code": "IRCTC",
        "name": "IRCTC Ltd",
        "sector": "Services",
        "industry": "Travel",
        "market_cap": 85000000000,
    },
    {
        "symbol": "LICHSGFIN",
        "nse_code": "LICHSGFIN",
        "name": "LIC Housing Finance Ltd",
        "sector": "Financial Services",
        "industry": "Housing Finance",
        "market_cap": 65000000000,
    },
    {
        "symbol": "BAJAJHLDNG",
        "nse_code": "BAJAJHLDNG",
        "name": "Bajaj Holdings & Investment Ltd",
        "sector": "Financial Services",
        "industry": "Investment",
        "market_cap": 145000000000,
    },
    {
        "symbol": "ESCORTS",
        "nse_code": "ESCORTS",
        "name": "Escorts Kubota Ltd",
        "sector": "Capital Goods",
        "industry": "Agricultural Equipment",
        "market_cap": 45000000000,
    },
    {
        "symbol": "VGUARD",
        "nse_code": "VGUARD",
        "name": "V-Guard Industries Ltd",
        "sector": "Consumer Goods",
        "industry": "Electricals",
        "market_cap": 25000000000,
    },
    {
        "symbol": "FINPIPE",
        "nse_code": "FINPIPE",
        "name": "Finolex Industries Ltd",
        "sector": "Materials",
        "industry": "Pipes",
        "market_cap": 15000000000,
    },
    {
        "symbol": "ASTRAL",
        "nse_code": "ASTRAL",
        "name": "Astral Ltd",
        "sector": "Materials",
        "industry": "Pipes",
        "market_cap": 55000000000,
    },
    {
        "symbol": "JUBLINFRA",
        "nse_code": "JUBLINFRA",
        "name": "Jubilant Infrapro Ltd",
        "sector": "Energy",
        "industry": "Infrastructure",
        "market_cap": 12000000000,
    },
    {
        "symbol": "GMRINFRA",
        "nse_code": "GMRINFRA",
        "name": "GMR Infrastructure Ltd",
        "sector": "Services",
        "industry": "Infrastructure",
        "market_cap": 45000000000,
    },
    {
        "symbol": "ADANITRANS",
        "nse_code": "ADANITRANS",
        "name": "Adani Transmission Ltd",
        "sector": "Energy",
        "industry": "Power Transmission",
        "market_cap": 285000000000,
    },
    {
        "symbol": "ADANIENT",
        "nse_code": "ADANIENT",
        "name": "Adani Enterprises Ltd",
        "sector": "Conglomerate",
        "industry": "Diversified",
        "market_cap": 385000000000,
    },
    {
        "symbol": "ADANIST",
        "nse_code": "ADANIST",
        "name": "Adani Total Gas Ltd",
        "sector": "Energy",
        "industry": "Gas Distribution",
        "market_cap": 145000000000,
    },
    {
        "symbol": "ABCAP",
        "nse_code": "ABCAP",
        "name": "Adani Capital Pvt Ltd",
        "sector": "Financial Services",
        "industry": "NBFC",
        "market_cap": 0,
    },
    {
        "symbol": "SPICEJET",
        "nse_code": "SPICEJET",
        "name": "SpiceJet Ltd",
        "sector": "Services",
        "industry": "Airlines",
        "market_cap": 15000000000,
    },
    {
        "symbol": "INDIGO",
        "nse_code": "INDIGO",
        "name": "InterGlobe Enterprises Ltd",
        "sector": "Services",
        "industry": "Airlines",
        "market_cap": 145000000000,
    },
    {
        "symbol": "GLOBE",
        "nse_code": "GLOBE",
        "name": "India Grid Trust",
        "sector": "Financial Services",
        "industry": "InvIT",
        "market_cap": 35000000000,
    },
    {
        "symbol": "POWERGRID",
        "nse_code": "POWERGRID",
        "name": "Power Grid Trust",
        "sector": "Financial Services",
        "industry": "InvIT",
        "market_cap": 145000000000,
    },
    {
        "symbol": "TATAINVEST",
        "nse_code": "TATAINVEST",
        "name": "Tata Investment Corporation",
        "sector": "Financial Services",
        "industry": "Investment",
        "market_cap": 45000000000,
    },
    {
        "symbol": "AAPL",
        "nse_code": "AAPL",
        "name": "Apple Inc",
        "sector": "Technology",
        "industry": "Electronics",
        "market_cap": 3000000000000,
    },
    {
        "symbol": "MSFT",
        "nse_code": "MSFT",
        "name": "Microsoft Corporation",
        "sector": "Technology",
        "industry": "Software",
        "market_cap": 2800000000000,
    },
    {
        "symbol": "GOOGL",
        "nse_code": "GOOGL",
        "name": "Alphabet Inc",
        "sector": "Technology",
        "industry": "Internet",
        "market_cap": 1800000000000,
    },
    {
        "symbol": "AMZN",
        "nse_code": "AMZN",
        "name": "Amazon.com Inc",
        "sector": "Services",
        "industry": "E-Commerce",
        "market_cap": 1600000000000,
    },
    {
        "symbol": "TSLA",
        "nse_code": "TSLA",
        "name": "Tesla Inc",
        "sector": "Automobile",
        "industry": "EV",
        "market_cap": 800000000000,
    },
    {
        "symbol": "NVDA",
        "nse_code": "NVDA",
        "name": "NVIDIA Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "market_cap": 2200000000000,
    },
    {
        "symbol": "META",
        "nse_code": "META",
        "name": "Meta Platforms Inc",
        "sector": "Technology",
        "industry": "Social Media",
        "market_cap": 1200000000000,
    },
]


async def seed_all_stocks():
    await init_db()
    async with AsyncSessionLocal() as session:
        # Use INSERT ... ON CONFLICT to handle duplicates
        stmt = insert(Company).values(
            [
                {
                    "symbol": stock["symbol"],
                    "nse_code": stock["nse_code"],
                    "bse_code": stock.get("bse_code"),
                    "name": stock["name"],
                    "isin": stock.get("isin"),
                    "sector": stock["sector"],
                    "industry": stock["industry"],
                    "market_cap": stock.get("market_cap"),
                    "listing_date": stock.get("listing_date"),
                    "face_value": stock.get("face_value", 10.0),
                }
                for stock in NSE_STOCKS
            ]
        )
        stmt = stmt.on_conflict_do_nothing(index_elements=["symbol"])
        await session.execute(stmt)
        await session.commit()

        # Count total
        result = await session.execute(select(Company))
        companies = result.scalars().all()
        print(f"Total companies in DB: {len(companies)}")


if __name__ == "__main__":
    asyncio.run(seed_all_stocks())
